const { app, BrowserWindow, ipcMain, shell } = require("electron");
const os = require("node:os"); const path = require("node:path"); const { spawn } = require("node:child_process");
const store = require("./local-store.cjs"); const { startNetworkServer } = require("./network-server.cjs");
const { configureUpdater } = require("./updater.cjs");
let mainWindow; let server; let printerAgent;
function lanAddresses() { const result = []; for (const entries of Object.values(os.networkInterfaces())) for (const entry of entries || []) if (entry.family === "IPv4" && !entry.internal) result.push(entry.address); return result; }
function startPrinterAgent() { const script = app.isPackaged ? path.join(process.resourcesPath, "app.asar.unpacked", "printer-agent", "DeliveryFlow.PrintAgent.ps1") : path.join(__dirname, "..", "printer-agent", "DeliveryFlow.PrintAgent.ps1"); printerAgent = spawn("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", script], { windowsHide: true, stdio: "ignore" }); printerAgent.unref(); }
function registerIpc() {
  ipcMain.handle("network:info", () => ({ mode: "server", configured: true, terminalId: "servidor", terminalName: "Servidor", serverHost: "127.0.0.1", serverPort: 3030, lanAddresses: lanAddresses(), waiterUrls: lanAddresses().map((ip) => `http://${ip}:3030/garcom`) }));
  ipcMain.handle("network:snapshot", () => store.networkSnapshot()); ipcMain.handle("network:save-entity", (_e,p) => store.saveEntity(p.entityType,p.entityId,p.data)); ipcMain.handle("network:delete-entity", (_e,p) => store.deleteEntity(p.entityType,p.entityId));
  ipcMain.handle("local:login", (_e,p) => store.login(p.username,p.password)); ipcMain.handle("local:list-users", () => store.listUsers()); ipcMain.handle("local:save-user", (_e,p) => store.saveUser(p.actorId,p.user)); ipcMain.handle("local:delete-user", (_e,p) => store.deleteUser(p.actorId,p.userId)); ipcMain.handle("local:authorize-manager", (_e,p) => store.authorizeManager(p.username,p.secret)); ipcMain.handle("local:list-audit", () => store.listAudit());
  ipcMain.handle("sync:enqueue", (_e,p) => { if (p.entityType === "order") return p.operation === "delete" ? store.deleteEntity("order",p.entityId) : store.saveEntity("order",p.entityId,{ ...(p.data || {}), networkId:p.entityId }); return store.enqueue(p.operation,p.entityType,p.entityId,p.data); }); ipcMain.handle("sync:pending", () => store.pendingSync()); ipcMain.handle("sync:mark", (_e,id) => store.markSynced(id));
  ipcMain.handle("cash:current", () => store.currentCash("servidor")); ipcMain.handle("cash:open", (_e,p) => store.openCash(p.actorId,p.openingAmount,p.openingNote,"servidor","Servidor")); ipcMain.handle("cash:close", (_e,p) => store.closeCash(p.actorId,p.cash)); ipcMain.handle("cash:movement", (_e,p) => store.addLocalCashMovement(p.actorId,p.sessionId,p.type,p.amount,p.reason)); ipcMain.handle("cash:movements", (_e,id) => store.listLocalCashMovements(id)); ipcMain.handle("cash:sessions", () => store.listLocalCashSessions());
}
app.whenReady().then(async () => { store.initializeLocalStore(); registerIpc(); server = await startNetworkServer({ store, publicRoot:path.resolve(__dirname,"..","out"), port:3030 }); startPrinterAgent(); mainWindow = new BrowserWindow({ width:1440,height:900,minWidth:1060,minHeight:680,show:false,autoHideMenuBar:true,icon:path.join(__dirname,"..","public","deliveryflow-icon.png"),webPreferences:{preload:path.join(__dirname,"preload.cjs"),contextIsolation:true,nodeIntegration:false,sandbox:false} }); mainWindow.loadURL("http://127.0.0.1:3030/?desktop=1&network=server"); mainWindow.once("ready-to-show",()=>{mainWindow.maximize();mainWindow.show();configureUpdater({window:mainWindow,channel:"server",beforeInstall:()=>store.backupDatabase()});}); mainWindow.webContents.setWindowOpenHandler(({url})=>{if(url.includes("accounts.google.com")||url.includes("firebaseapp.com"))return{action:"allow"};if(url.startsWith("https://"))shell.openExternal(url);return{action:"deny"};}); });
app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit();}); app.on("before-quit",()=>{server?.close();if(printerAgent&&!printerAgent.killed)printerAgent.kill();});
